<?php

/**
 * PlugintdVideoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    tdVideoPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class PlugintdVideoTable extends Doctrine_Table
{
  /**
   * Returns DQL query retrieving all active video files.
   *
   * @return Doctrine_Query
   */
  static public function getActiveVideosQuery()
  {
    return Doctrine_Query::create()
             ->from('tdVideo v')
             ->where('v.active = "1"');
  }

  /**
   * Returns DQL query retrieving active video file given by file.
   *
   * @param String $file - video file
   * @return Doctrine_Query
   */
  static public function getActiveVideoByFileQuery($file)
  {
    return Doctrine_Query::create()
             ->from('tdVideo v')
             ->where('v.file = ?', $file)
             ->andWhere('v.active = "1"');
  }

  /**
   * Returns DQL query retrieving video files selected by ids.
   *
   * @param Array $ids - Identifiers of selected links.
   * @return Doctrine_Query
   */
  static public function getSelectedVideosQuery($ids)
  {
    return Doctrine_Query::create()
             ->from('tdVideo v')
             ->whereIn('v.id', $ids);
  }
}