<?php

/**
 * PlugintdVideo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    tdVideoPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdVideo extends BasetdVideo
{
  /**
   * Returns short description of the video.
   *
   * @return String - short description.
   */
  public function getDescriptionShort()
  {
    return tdTools::getMbShortenedString($this->getDescription(), sfConfig::get('td_short_text_sign_count'));
  }

  /**
   * Activates the video file.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the video file.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }

  /**
   * Attempts to delete the video flv file before record is deleted.
   *
   * @param Doctrine_Event $event
   */
  public function preDelete($event)
  {
    $file_path = sfConfig::get('td_video_upload_dir').'/'.$this->getFile();
    if (file_exists($file_path))
      unlink($file_path);
  }
}