<?php

/**
 * PlugintdVideo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    tdVideoPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdVideo extends BasetdVideo
{
  public function getDescriptionShort()
  {
    return mb_substr($this->getDescription(), 0, 200).'...';
  }

  /**
   * Activates the video file.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the video file.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }
}