td_sample_video:
  url:   /video
  param: { module: tdSampleVideo, action: index }

td_sample_video_show:
  url:   /video/:file
  param: { module: tdSampleVideo, action: show }
  options:
    segment_separators: ['/'] # disabling '.' separator

# ajax actions

ajax_video_activate:
  url:   /ajax-video-activate/:id
  param: { module: td_video, action: activate }
  requirements:
    id: \d+

ajax_video_deactivate:
  url:   /ajax-video-deactivate/:id
  param: { module: td_video, action: deactivate }
  requirements:
    id: \d+

td_video:
  class: sfDoctrineRouteCollection
  options:
    model:                tdVideo
    module:               td_video
    prefix_path:          /td_video
    column:               id
    with_wildcard_routes: true
