generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tdVideo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          td_video
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing
    i18n_catalogue:        sf_admin

    config:
      actions: ~
      fields:
        name:
          label: Nazwa
        description:
          label: Opis
        description_short:
          label: Skrócony opis
        author:
          label: Autor
        file:
          label: Plik
        _file_show:
          label: Podgląd
        recorded_at:
          label: Nagrano
        active:
          label: Aktywny
          help: if the link shall be visible on the frontend website
        created_at:
          label: Utworzono
        updated_at:
          label: Zmieniono
      list:
        title: Video file list
        batch_actions:
          _delete: ~
          activate: ~
          deactivate: ~
        object_actions:
          _edit: ~
          _delete: ~
          activate: ~
          deactivate: ~
        display: [ active, name, author, recorded_at, description_short, updated_at ]
        max_per_page: 10
        layout: stacked
        params: |
          <strong>Nazwa</strong>: <i>%%name%%</i> %%active%%
          <br />
          <strong>Autor</strong>: <i>%%author%%</i>
          <br />
          <strong>Nagrano</strong>: <i>%%recorded_at%%</i>
          <br />
          <strong>Opis</strong>: <div class="text_box">%%description_short%%</div>
          <br />
          <strong>utworzono</strong>: <i>%%created_at%%</i>
          <br />
          <strong>zmieniono</strong>: <i>%%updated_at%%</i>
      filter:  ~
      form:
        fields:
          name:
            attributes: { size: 80 }
          author:
            attributes: { size: 80 }
          description:
            attributes: { cols: 80, rows: 16 }
      edit:
        title: Edit video file
        display: [ name, author, description, _file_show, file, recorded_at, active ]
      new:
        title: New video file
